services:
    _defaults:
        public: false

    LazyHttpClientBundle\Client\Manager:
        arguments:
            - ~

    LazyHttpClientBundle\Client\QueryContainer:
        arguments:
            - ~

    LazyHttpClientBundle\Profiler\RequestCollector:
        tags:
            -:
              name:     data_collector
              template: '@LazyHttpClient/profiler/request_profiler.html.twig'
              id:       'lazy_http_client'

    LazyHttpClientBundle\Client\Logger:
        tags:
            - { name: monolog.logger, channel: lazy_http_client }

    LazyHttpClientBundle\Client\HttpQueue:
        arguments:
            - '@monolog.logger.lazy_http_client'
            - '@LazyHttpClientBundle\Profiler\RequestCollector'

    LazyHttpClientBundle\Client\LazyFactory:
        arguments:
            - '@LazyHttpClientBundle\Client\HttpQueue'
