services:
    _defaults:
        public: false

    LazyHttpClientBundle\Client\Manager:
        arguments:
            - ~

    LazyHttpClientBundle\Client\QueryContainer:
        arguments:
            - ~

    LazyHttpClientBundle\Client\Logger:
        tags:
            - { name: monolog.logger, channel: lazy_http_client }

    LazyHttpClientBundle\Client\HttpQueue:
        arguments:
            - '@monolog.logger.lazy_http_client'

    LazyHttpClientBundle\Client\LazyFactory:
        arguments:
            - '@LazyHttpClientBundle\Client\HttpQueue'
